export { default as BackgroundMovement } from './BackgroundMovement'
export { default as BoxedImageWithText } from './BoxedImageWithText'
export { default as Hero } from './Hero'
export { default as Posts } from './Posts'
export { default as PricingTable1 } from './PricingTable1'
export { default as Projects } from './Projects'
export { default as TextWithBackground } from './TextWithBackground'
